#include <iostream>
#include <cmath>
#include "iforest_export.h"

using namespace std;



float path_length(
    const int *feature,
    const float *threshold,
    const int *left,
    const int *right,
    float *x)
{
    int node = 0;
    float depth = 0.0f;

    while (left[node] != -1 && right[node] != -1)
    {
        int f = feature[node];

        if (x[f] <= threshold[node])
            node = left[node];
        else
            node = right[node];

        depth += 1.0f;
    }

    return depth;
}


float compute_iforest_score(float *x)
{
    float total_path = 0.0f;

    for (int i = 0; i < NUM_TREES; i++)
    {
        const int *feature;
        const float *threshold;
        const int *left;
        const int *right;

        switch (i)
        {
#define TREE_CASE(N) \
case N: \
    feature = tree_##N##_feature; \
    threshold = tree_##N##_threshold; \
    left = tree_##N##_left; \
    right = tree_##N##_right; \
    break;
                TREE_CASE(0)
                TREE_CASE(1)
                TREE_CASE(2)
                TREE_CASE(3)
                TREE_CASE(4)
                TREE_CASE(5)
                TREE_CASE(6)
                TREE_CASE(7)
                TREE_CASE(8)
                TREE_CASE(9)
                TREE_CASE(10)
                TREE_CASE(11)
                TREE_CASE(12)
                TREE_CASE(13)
                TREE_CASE(14)
                TREE_CASE(15)
                TREE_CASE(16)
                TREE_CASE(17)
                TREE_CASE(18)
                TREE_CASE(19)
                TREE_CASE(20)
                TREE_CASE(21)
                TREE_CASE(22)
                TREE_CASE(23)
                TREE_CASE(24)
                TREE_CASE(25)
                TREE_CASE(26)
                TREE_CASE(27)
                TREE_CASE(28)
                TREE_CASE(29)
                TREE_CASE(30)
                TREE_CASE(31)
                TREE_CASE(32)
                TREE_CASE(33)
                TREE_CASE(34)
                TREE_CASE(35)
                TREE_CASE(36)
                TREE_CASE(37)
                TREE_CASE(38)
                TREE_CASE(39)
                TREE_CASE(40)
                TREE_CASE(41)
                TREE_CASE(42)
                TREE_CASE(43)
                TREE_CASE(44)
                TREE_CASE(45)
                TREE_CASE(46)
                TREE_CASE(47)
                TREE_CASE(48)
                TREE_CASE(49)
                TREE_CASE(50)
                TREE_CASE(51)
                TREE_CASE(52)
                TREE_CASE(53)
                TREE_CASE(54)
                TREE_CASE(55)
                TREE_CASE(56)
                TREE_CASE(57)
                TREE_CASE(58)
                TREE_CASE(59)
                TREE_CASE(60)
                TREE_CASE(61)
                TREE_CASE(62)
                TREE_CASE(63)
                TREE_CASE(64)
                TREE_CASE(65)
                TREE_CASE(66)
                TREE_CASE(67)
                TREE_CASE(68)
                TREE_CASE(69)
                TREE_CASE(70)
                TREE_CASE(71)
                TREE_CASE(72)
                TREE_CASE(73)
                TREE_CASE(74)
                TREE_CASE(75)
                TREE_CASE(76)
                TREE_CASE(77)
                TREE_CASE(78)
                TREE_CASE(79)
                TREE_CASE(80)
                TREE_CASE(81)
                TREE_CASE(82)
                TREE_CASE(83)
                TREE_CASE(84)
                TREE_CASE(85)
                TREE_CASE(86)
                TREE_CASE(87)
                TREE_CASE(88)
                TREE_CASE(89)
                TREE_CASE(90)
                TREE_CASE(91)
                TREE_CASE(92)
                TREE_CASE(93)
                TREE_CASE(94)
                TREE_CASE(95)
                TREE_CASE(96)
                TREE_CASE(97)
                TREE_CASE(98)
                TREE_CASE(99)
                TREE_CASE(100)
                TREE_CASE(101)
                TREE_CASE(102)
                TREE_CASE(103)
                TREE_CASE(104)
                TREE_CASE(105)
                TREE_CASE(106)
                TREE_CASE(107)
                TREE_CASE(108)
                TREE_CASE(109)
                TREE_CASE(110)
                TREE_CASE(111)
                TREE_CASE(112)
                TREE_CASE(113)
                TREE_CASE(114)
                TREE_CASE(115)
                TREE_CASE(116)
                TREE_CASE(117)
                TREE_CASE(118)
                TREE_CASE(119)
                TREE_CASE(120)
                TREE_CASE(121)
                TREE_CASE(122)
                TREE_CASE(123)
                TREE_CASE(124)
                TREE_CASE(125)
                TREE_CASE(126)
                TREE_CASE(127)
                TREE_CASE(128)
                TREE_CASE(129)
                TREE_CASE(130)
                TREE_CASE(131)
                TREE_CASE(132)
                TREE_CASE(133)
                TREE_CASE(134)
                TREE_CASE(135)
                TREE_CASE(136)
                TREE_CASE(137)
                TREE_CASE(138)
                TREE_CASE(139)
                TREE_CASE(140)
                TREE_CASE(141)
                TREE_CASE(142)
                TREE_CASE(143)
                TREE_CASE(144)
                TREE_CASE(145)
                TREE_CASE(146)
                TREE_CASE(147)
                TREE_CASE(148)
                TREE_CASE(149)
                TREE_CASE(150)
                TREE_CASE(151)
                TREE_CASE(152)
                TREE_CASE(153)
                TREE_CASE(154)
                TREE_CASE(155)
                TREE_CASE(156)
                TREE_CASE(157)
                TREE_CASE(158)
                TREE_CASE(159)
                TREE_CASE(160)
                TREE_CASE(161)
                TREE_CASE(162)
                TREE_CASE(163)
                TREE_CASE(164)
                TREE_CASE(165)
                TREE_CASE(166)
                TREE_CASE(167)
                TREE_CASE(168)
                TREE_CASE(169)
                TREE_CASE(170)
                TREE_CASE(171)
                TREE_CASE(172)
                TREE_CASE(173)
                TREE_CASE(174)
                TREE_CASE(175)
                TREE_CASE(176)
                TREE_CASE(177)
                TREE_CASE(178)
                TREE_CASE(179)
                TREE_CASE(180)
                TREE_CASE(181)
                TREE_CASE(182)
                TREE_CASE(183)
                TREE_CASE(184)
                TREE_CASE(185)
                TREE_CASE(186)
                TREE_CASE(187)
                TREE_CASE(188)
                TREE_CASE(189)
                TREE_CASE(190)
                TREE_CASE(191)
                TREE_CASE(192)
                TREE_CASE(193)
                TREE_CASE(194)
                TREE_CASE(195)
                TREE_CASE(196)
                TREE_CASE(197)
                TREE_CASE(198)
                TREE_CASE(199)
                TREE_CASE(200)
                TREE_CASE(201)
                TREE_CASE(202)
                TREE_CASE(203)
                TREE_CASE(204)
                TREE_CASE(205)
                TREE_CASE(206)
                TREE_CASE(207)
                TREE_CASE(208)
                TREE_CASE(209)
                TREE_CASE(210)
                TREE_CASE(211)
                TREE_CASE(212)
                TREE_CASE(213)
                TREE_CASE(214)
                TREE_CASE(215)
                TREE_CASE(216)
                TREE_CASE(217)
                TREE_CASE(218)
                TREE_CASE(219)
                TREE_CASE(220)
                TREE_CASE(221)
                TREE_CASE(222)
                TREE_CASE(223)
                TREE_CASE(224)
                TREE_CASE(225)
                TREE_CASE(226)
                TREE_CASE(227)
                TREE_CASE(228)
                TREE_CASE(229)
                TREE_CASE(230)
                TREE_CASE(231)
                TREE_CASE(232)
                TREE_CASE(233)
                TREE_CASE(234)
                TREE_CASE(235)
                TREE_CASE(236)
                TREE_CASE(237)
                TREE_CASE(238)
                TREE_CASE(239)
                TREE_CASE(240)
                TREE_CASE(241)
                TREE_CASE(242)
                TREE_CASE(243)
                TREE_CASE(244)
                TREE_CASE(245)
                TREE_CASE(246)
                TREE_CASE(247)
                TREE_CASE(248)
                TREE_CASE(249)
                TREE_CASE(250)
                TREE_CASE(251)
                TREE_CASE(252)
                TREE_CASE(253)
                TREE_CASE(254)
                TREE_CASE(255)
                TREE_CASE(256)
                TREE_CASE(257)
                TREE_CASE(258)
                TREE_CASE(259)
                TREE_CASE(260)
                TREE_CASE(261)
                TREE_CASE(262)
                TREE_CASE(263)
                TREE_CASE(264)
                TREE_CASE(265)
                TREE_CASE(266)
                TREE_CASE(267)
                TREE_CASE(268)
                TREE_CASE(269)
                TREE_CASE(270)
                TREE_CASE(271)
                TREE_CASE(272)
                TREE_CASE(273)
                TREE_CASE(274)
                TREE_CASE(275)
                TREE_CASE(276)
                TREE_CASE(277)
                TREE_CASE(278)
                TREE_CASE(279)
                TREE_CASE(280)
                TREE_CASE(281)
                TREE_CASE(282)
                TREE_CASE(283)
                TREE_CASE(284)
                TREE_CASE(285)
                TREE_CASE(286)
                TREE_CASE(287)
                TREE_CASE(288)
                TREE_CASE(289)
                TREE_CASE(290)
                TREE_CASE(291)
                TREE_CASE(292)
                TREE_CASE(293)
                TREE_CASE(294)
                TREE_CASE(295)
                TREE_CASE(296)
                TREE_CASE(297)
                TREE_CASE(298)
                TREE_CASE(299)
                TREE_CASE(300)
                TREE_CASE(301)
                TREE_CASE(302)
                TREE_CASE(303)
                TREE_CASE(304)
                TREE_CASE(305)
                TREE_CASE(306)
                TREE_CASE(307)
                TREE_CASE(308)
                TREE_CASE(309)
                TREE_CASE(310)
                TREE_CASE(311)
                TREE_CASE(312)
                TREE_CASE(313)
                TREE_CASE(314)
                TREE_CASE(315)
                TREE_CASE(316)
                TREE_CASE(317)
                TREE_CASE(318)
                TREE_CASE(319)
                TREE_CASE(320)
                TREE_CASE(321)
                TREE_CASE(322)
                TREE_CASE(323)
                TREE_CASE(324)
                TREE_CASE(325)
                TREE_CASE(326)
                TREE_CASE(327)
                TREE_CASE(328)
                TREE_CASE(329)
                TREE_CASE(330)
                TREE_CASE(331)
                TREE_CASE(332)
                TREE_CASE(333)
                TREE_CASE(334)
                TREE_CASE(335)
                TREE_CASE(336)
                TREE_CASE(337)
                TREE_CASE(338)
                TREE_CASE(339)
                TREE_CASE(340)
                TREE_CASE(341)
                TREE_CASE(342)
                TREE_CASE(343)
                TREE_CASE(344)
                TREE_CASE(345)
                TREE_CASE(346)
                TREE_CASE(347)
                TREE_CASE(348)
                TREE_CASE(349)
                TREE_CASE(350)
                TREE_CASE(351)
                TREE_CASE(352)
                TREE_CASE(353)
                TREE_CASE(354)
                TREE_CASE(355)
                TREE_CASE(356)
                TREE_CASE(357)
                TREE_CASE(358)
                TREE_CASE(359)
                TREE_CASE(360)
                TREE_CASE(361)
                TREE_CASE(362)
                TREE_CASE(363)
                TREE_CASE(364)
                TREE_CASE(365)
                TREE_CASE(366)
                TREE_CASE(367)
                TREE_CASE(368)
                TREE_CASE(369)
                TREE_CASE(370)
                TREE_CASE(371)
                TREE_CASE(372)
                TREE_CASE(373)
                TREE_CASE(374)
                TREE_CASE(375)
                TREE_CASE(376)
                TREE_CASE(377)
                TREE_CASE(378)
                TREE_CASE(379)
                TREE_CASE(380)
                TREE_CASE(381)
                TREE_CASE(382)
                TREE_CASE(383)
                TREE_CASE(384)
                TREE_CASE(385)
                TREE_CASE(386)
                TREE_CASE(387)
                TREE_CASE(388)
                TREE_CASE(389)
                TREE_CASE(390)
                TREE_CASE(391)
                TREE_CASE(392)
                TREE_CASE(393)
                TREE_CASE(394)
                TREE_CASE(395)
                TREE_CASE(396)
                TREE_CASE(397)
                TREE_CASE(398)
                TREE_CASE(399)



#undef TREE_CASE

        default:
            continue;
        }

        total_path += path_length(feature, threshold, left, right, x);
    }

    float avg_path = total_path / NUM_TREES;

    return avg_path;
}


int main()
{
    cout << "Isolation Forest C++ Validation\n";

    //  Use SCALED feature vector from Python
    float test_features[NUM_FEATURES] = {
        0.12, -0.55, 0.33, 0.21, -0.18,
        0.45, -0.11, 0.09, -0.03, 0.88,
        0.01, -0.4, 0.15, 0.2, -0.09,
        0.04, 0.3
    };

    float score = compute_iforest_score(test_features);

    cout << "Average Path Length: " << score << endl;

    return 0;
}
